name = "dev-toolkit-pro"
main = "server/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[vars]
FRONTEND_URL = "https://www.928496.xyz"
OAUTH_CALLBACK_BASE_URL = "https://www.928496.xyz"
GITHUB_CLIENT_ID = "Ov23liSf1CrzpHhliIJ2"

[assets]
directory = "dist"
binding = "ASSETS"
html_handling = "none"
not_found_handling = "none"

[[d1_databases]]
binding = "DB"
database_name = "dev-toolkit-db"
database_id = "2ff968e4-26bc-4eb5-b82e-9949cdce06d5"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "SHARE_KV"
id = "3d66c87ff95749f2a5e74306633d574e"

[[r2_buckets]]
binding = "SHARE_R2"
bucket_name = "share-files"

[observability]
enabled = false
