name = "dev-toolkit-pro"
main = "server/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "dev-toolkit-db"
database_id = "2ff968e4-26bc-4eb5-b82e-9949cdce06d5"
migrations_dir = "migrations"

[observability]
enabled = true
